language: python
python:
  - "2.7"      # Python 2.7 reached the end of its life on January 1st, 2020.
  #- "3.4"
  #- "3.5"
  - "3.6"      # current default Python on Travis CI
  #- "3.7"
  #- "3.8"
  # We can't realistically run dev or nightly branches
  #- "3.8-dev"  # 3.8 development branch
  #- "nightly"  # nightly build

env:
  - DOCKER_COMPOSE_VERSION=1.27.4

services:
  - docker

before_install:
  # Update docker-compose version
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  
  # Build asterisk on python:${$TRAVIS_PYTHON_VERSION}-alpine
  - docker-compose -f test/docker-compose.yml up -d
  
  - echo $TRAVIS_APP_HOST

install:
  # Install package and dependencies
  - pip install .
  - pip install coverage coveralls

# command to run tests
script:
  - docker exec -it test_asterisk_1 sh "${TRAVIS_BUILD_DIR}/test/setup.sh"  
  - coverage run -a --rcfile=.coveragerc.travis -m pytest
  
after_success:
  # Make .coverage file for asterisk side readable
  - sudo chown travis:travis .coverage.asterisk
  - sudo chmod 666 .coverage.asterisk
  # Combine .coverage files for asterisk and travis
  - coverage combine --append .coverage.asterisk .coverage.travis
  # Print coverage report data
  - coverage report -m
  # Submit coverage to coveralls.io
  - coveralls
