language: python
python:
#  - "2.7"
#  - "3.4"
#  - "3.5"
  - "3.6"      # current default Python on Travis CI
#  - "3.7"
#  - "3.8"

# We can't realistically run dev or nightly branches
#  - "3.8-dev"  # 3.8 development branch
#  - "nightly"  # nightly build

env:
  - DOCKER_COMPOSE_VERSION=1.27.4

services:
  - docker

before_install:
  #- echo Python Version=$TRAVIS_PYTHON_VERSION
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose -f test/docker-compose.yml up -d --build

# command to install dependencies
install:
  - pip install .
  - pip install coverage coveralls
#  - pip install pytest-cov

# command to run tests
script:
  #- pytest
  - coverage run --source asterisk -m pytest -o cache_dir=/dev/null
  
after_success:
  - coverage report -m
  - coveralls
#  - coverage run --source=my_package setup.py test
